//
//  Actions.swift
//  ReduxCoreFromUkitToSwiftUI
//
//  Created by Yaroslav Golinskiy on 21/08/2025.
//

import Foundation
import ReduxCore

/// Namespace for all application actions
/// Organized by feature/middleware for better structure
/// Namespace для всіх дій додатку
/// Організовано за функціоналом/middleware для кращої структури
enum Actions {
    
    // MARK: - Application Lifecycle Actions
    // MARK: - Дії життєвого циклу додатку
    
    /// Actions triggered by app lifecycle events (from ScenePhase)
    /// Дії викликані подіями життєвого циклу додатку (з ScenePhase)
    enum AppLifecycle {
        
        /// App became active (foreground and ready)
        /// Додаток став активним (на передньому плані і готовий)
        struct DidBecomeActive: Action {}
        
        /// App will resign active (before background/inactive)
        /// Додаток втратить активність (перед фоном/неактивністю)
        struct WillResignActive: Action {}
        
        /// App entered background
        /// Додаток перейшов у фоновий режим
        struct DidEnterBackground: Action {}
        
        /// App will enter foreground
        /// Додаток переходить на передній план
        struct WillEnterForeground: Action {}
        
        /// App finished launching
        /// Додаток завершив запуск
        struct DidFinishLaunch: Action {}
    }
    
    // MARK: - UI Actions
    // MARK: - UI дії
    
    /// Actions from main view interactions
    /// Дії від взаємодії з головним view
    enum MainViewPresenter {
        
        /// User clicked the torch toggle button
        /// Користувач клікнув кнопку перемикання ліхтарика
        struct Click: Action {}
    }
    
    // MARK: - Middleware Actions
    // MARK: - Дії Middleware
    
    /// Actions generated by FlashlightMiddleware
    /// Дії згенеровані FlashlightMiddleware
    enum FlashlightMiddleware {
        
        /// Torch state changed (success)
        /// Стан ліхтарика змінено (успішно)
        struct Changed: Action {
            let isEnabled: Bool
        }
        
        /// Torch operation failed
        /// Операція з ліхтариком не вдалася
        struct Failed: Action {
            let error: Error
        }
    }
    
    /// Actions generated by UpdateDateMiddleware
    /// Дії згенеровані UpdateDateMiddleware
    enum UpdateDateMiddleware {
        
        /// Current date/time update
        /// Оновлення поточної дати/часу
        struct UpdateCurrent: Action {
            let date: Date
        }
    }
}
