//
//  Actions.swift
//  ReduxCoreFromUkitToSwiftUI
//
//  Created by Yaroslav Golinskiy on 21/08/2025.
//

import Foundation
import ReduxCore

/// Namespace for all application actions
/// Organized by feature/middleware for better structure
enum Actions {
    
    // MARK: - Application Lifecycle Actions
    
    /// Actions triggered by app lifecycle events (from ScenePhase)
    enum AppLifecycle {
        
        /// App became active (foreground and ready)
        struct DidBecomeActive: Action {}
        
        /// App will resign active (before background/inactive)
        struct WillResignActive: Action {}
        
        /// App entered background
        struct DidEnterBackground: Action {}
        
        /// App will enter foreground
        struct WillEnterForeground: Action {}
        
        /// App finished launching
        struct DidFinishLaunch: Action {}
    }
    
    // MARK: - UI Actions
    
    /// Actions from main view interactions
    enum MainViewPresenter {
        
        /// User clicked the torch toggle button
        struct Click: Action {}
    }
    
    // MARK: - Middleware Actions
    
    /// Actions generated by FlashlightMiddleware
    enum FlashlightMiddleware {
        
        /// Torch state changed (success)
        struct Changed: Action {
            let isEnabled: Bool
        }
        
        /// Torch operation failed
        struct Failed: Action {
            let error: Error
        }
    }
    
    /// Actions generated by UpdateDateMiddleware
    enum UpdateDateMiddleware {
        
        /// Current date/time update
        struct UpdateCurrent: Action {
            let date: Date
        }
    }
}
